#ifndef CONFIG_H
#define CONFIG_H

#define PEACHOS_HEAP_SIZE_BYTES 1024 * 1024 * 100
#define PEACHOS_HEAP_BLOCK_SIZE 4096
#define PEACHOS_HEAP_SIZE_BLOCKS \
  PEACHOS_HEAP_SIZE_BYTES / PEACHOS_HEAP_BLOCK_SIZE
#define PEACHOS_HEAP_ADDRESS 0x1000000

#endif  // CONFIG_H
